#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $POSTGRES_USER_A WITH PASSWORD '$POSTGRES_PASSWORD_A';
  CREATE USER postgres WITH PASSWORD 'postgres';
  CREATE DATABASE $POSTGRES_DB_A;
  ALTER USER root WITH SUPERUSER;



EOSQL
